### PR TITLE
Bug fix: correct error calculation for JetFitObjects in ZH5CFit

### PR DESCRIPTION
**Pull request by yradkhorrami**
BEGINRELEASENOTES

1. derivatives for calculating errors of jet angles are corrected now:
       **d_theta / d_px = px . pz / ( P^2 . pT )**
       **d_theta / d_py = py . pz / ( P^2 . pT )**
       **d_theta / d_pz = -pT / P^2**
2. JetResTheta is corrected (sqrt was missed):
   **JetResTheta = sqrt ( (d_theta / d_px)^2 * SigPx2 + ... )**

3. JetResPhi is corrected (sqrt was missed, d_theta / d_px and d_theta / d_py should be replaced by d_phi / d_px and d_phi / d_py ):
   **JetResPhi = sqrt ( (d_phi / d_px)^2 * SigPx2 + ...  )**

ENDRELEASENOTES

### CODE REVIEW

**Review by rete — CHANGES_REQUESTED** [review]
@yradkhorrami Thanks for the fix. You should normally work from another branch before you make a pull request. But this is fine for today.
Question: why do you need MarlinUtil for this PR? The changes do not require the MarlinUtil library

**Comment by rete** [comment]
Also you can shorten the release note message which is actually longer than your changes ;-).
Get to the point.

**Comment by yradkhorrami** [comment]
> @yradkhorrami Thanks for the fix. You should normally work from another branch before you make a pull request. But this is fine for today.

Thanks Remi, next time I will work from another branch.

> Question: why do you need MarlinUtil for PR? The changes do not require the MarlinUtil library

The next step for this Marlin processor is to add ZHllqqFit which does KinFit on 2 leptons + 2 jets events. The momentum of 2 leptons are calculated using the magnetic field of detector
Do you suggest to make these changes by adding ZHllqqFit?

**Comment by rete** [comment]
This PR is a bug fix. I suggest to remove MarlinUtil from now. 
Add it to your next PR with features.

**Comment by yradkhorrami** [comment]
> This PR is a bug fix. I suggest to remove MarlinUtil from now.
> Add it to your next PR with features.

So I think I should do a new PR from a new branch (non-master) with only bug-fix related stuff.

**Comment by rete** [comment]
You can always make changes to this PR by pushing new commits

**Comment by yradkhorrami** [comment]
> You can always make changes to this PR by pushing new commits

I think I have made changes to this PR. Could you please check it?

**Comment by rete** [comment]
The travis-ci page says everything is OK: https://travis-ci.org/github/iLCSoft/MarlinKinfitProcessors/pull_requests

Github seems stuck with it. All looks alright, I merge it.

**Review by rete — APPROVED** [review]

**Comment by rete** [comment]
@yradkhorrami  Please update your release note message. It is way too long for the fix. A few lines are enough, you don't have to describe all formulas.

**Comment by yradkhorrami** [comment]
> @yradkhorrami Please update your release note message. It is way too long for the fix. A few lines are enough, you don't have to describe all formulas.

Ok, I shortened the release note. Thanks Remi.

**Pull request merged**
