### PR TITLE
Bug fix: correct error calculation fot JetFitObjects in ZH5CFit

### PR DESCRIPTION
**Pull request by yradkhorrami**
BEGINRELEASENOTES
- Thank you for writing the text to appear in the release notes. It will show up
  exactly as it appears between the two bold lines
- ...

ENDRELEASENOTES

### CODE REVIEW

**Comment by yradkhorrami** [comment]
Calculation of errors of jet angles is corrected

**Review by JennyListDESY — CHANGES_REQUESTED** [review]
Hi Yasser,
I agree now with the implemented  derivatives, apart from a minus sign in dth_dpz - shouldn't
this be -pt/p^2 ?

Sorry for the confusion I created - but at least we are really sure now about this point ;-)

However:
1) you now re-calculate pt (or pt^2) 5 times, using two different calculations:
   3x  std::sqrt( 1 - ( pz2 / std::pow(p,2) ) )
   2x  px2+py2
   please instead define a variable 
   pt2 = px2+py2
   and use this always - directly or as sqrt(pt2)

So then:

	     dth_dpx =	( Px * Pz ) / ( std::pow( P , 2 ) * std::sqrt(pt2) );
	     dth_dpy =	( Py * Pz ) / ( std::pow( P , 2 ) * std::sqrt(pt2) );
	     dth_dpz =	-std::sqrt( pt2) / std::pow(P,2);    ! MINUS SIGN
             dphi_dpx=(-Py)/pt2;
             dphi_dpy=(Px)/pt2;

2) still it seems to me that the ZHllqqFit files are part of the pull request.
   Can you change that? If git doesn't allow to take them out again, I won't be religious about this.

3) Please add a text to the release notes!

**Comment by rete** [comment]
This pull request looks weird... Github says that you are not using a fork or anything: "`unknown repository`". 
@yradkhorrami Can you fork this package, push your changes to a feature branch and open a new pull request with only the changes you want please?

**Comment by yradkhorrami** [comment]
> This pull request looks weird... Github says that you are not using a fork or anything: "`unknown repository`".
> @yradkhorrami Can you fork this package, push your changes to a feature branch and open a new pull request with only the changes you want please?

Hi Remi,
Thanks for the tutorial.
I have created a new PR.

**Pull request closed without merging**
