### PR TITLE
Bug fix: correct CovMatrix elements

### PR DESCRIPTION
**Pull request by yradkhorrami**
BEGINRELEASENOTES
- FourMomentumCovMat, algebraImplementation:
   - the lower triangle of CovMatrix should be applied for correct diagonal and off-diagonal elements

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
Travis-CI is OK. Fails to report as usual...

**Comment by andresailer** [comment]
Trying to trigger the CI, closing and opening PR

**Comment by andresailer** [comment]
Travis isn't happy about the commits in this PR.
image
https://travis-ci.com/github/iLCSoft/MarlinKinfitProcessors/requests

**Comment by andresailer** [comment]
Pushing #13 caused the builds to run also for this PR. Maybe @yradkhorrami  isn't registered in travis-ci and that's why they were rejected, but no definite proof.

There is also a problem with the required checks pointing still to the "Travis ci .org status" and not the new "Travis CI - Pull request"

**Review by JennyListDESY — APPROVED** [review]
Hi Remi,
the new changes from June 22 are just the indices of the covariance matrix elements, which is fully ok.
The earlier commits (~June 10) were the partial derivatievs we iterated on, they are finally also ok.

**Pull request merged**
